---
name: main

on:
  push:
    branches:
      - master
      - 'ver/**'
  pull_request:
    branches:
      - master
      - 'ver/**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          pureskillgg_username: ${{ secrets.JFROG_USER }}
          pureskillgg_password: ${{ secrets.JFROG_API_KEY }}
      - name: Test
        run: make test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          pureskillgg_username: ${{ secrets.JFROG_USER }}
          pureskillgg_password: ${{ secrets.JFROG_API_KEY }}
      - name: Lint
        run: make lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          pureskillgg_username: ${{ secrets.JFROG_USER }}
          pureskillgg_password: ${{ secrets.JFROG_API_KEY }}
      - name: Build
        run: make build
