---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  jfrog:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          pureskillgg_username: ${{ secrets.JFROG_USER }}
          pureskillgg_password: ${{ secrets.JFROG_API_KEY }}
      - name: Publish
        run: poetry publish --build --skip-existing -u $USERNAME -p $PASSWORD -r pureskillgg
        env:
          USERNAME: ${{ secrets.JFROG_USER }}
          PASSWORD: ${{ secrets.JFROG_API_KEY }}
