---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  jfrog:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Setup Poetry
        uses: gr1n/setup-poetry@v4
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install
        env:
          POETRY_HTTP_BASIC_PURESKILLGG_USERNAME: ${{ secrets.JFROG_USER }}
          POETRY_HTTP_BASIC_PURESKILLGG_PASSWORD: ${{ secrets.JFROG_API_KEY }}
      - name: Build
        run: make build
      - name: Publish
        run: make publish
        env:
          TWINE_USERNAME: ${{ secrets.JFROG_USER }}
          TWINE_PASSWORD: ${{ secrets.JFROG_API_KEY }}
